// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/currency.proto

package grpc_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currencies int32

const (
	Currencies_USD Currencies = 0
	Currencies_JPY Currencies = 1
	Currencies_BGN Currencies = 2
	Currencies_CZK Currencies = 3
	Currencies_DKK Currencies = 4
	Currencies_GBP Currencies = 5
	Currencies_HUF Currencies = 6
	Currencies_PLN Currencies = 7
	Currencies_RON Currencies = 8
	Currencies_SEK Currencies = 9
	Currencies_CHF Currencies = 10
	Currencies_ISK Currencies = 11
	Currencies_NOK Currencies = 12
	Currencies_HRK Currencies = 13
	Currencies_TRY Currencies = 14
	Currencies_AUD Currencies = 15
	Currencies_BRL Currencies = 16
	Currencies_CAD Currencies = 17
	Currencies_CNY Currencies = 18
	Currencies_HKD Currencies = 19
	Currencies_IDR Currencies = 20
	Currencies_ILS Currencies = 21
	Currencies_INR Currencies = 22
	Currencies_KRW Currencies = 23
	Currencies_MXN Currencies = 24
	Currencies_MYR Currencies = 25
	Currencies_NZD Currencies = 26
	Currencies_PHP Currencies = 27
	Currencies_SGD Currencies = 28
	Currencies_THB Currencies = 29
	Currencies_ZAR Currencies = 30
)

// Enum value maps for Currencies.
var (
	Currencies_name = map[int32]string{
		0:  "USD",
		1:  "JPY",
		2:  "BGN",
		3:  "CZK",
		4:  "DKK",
		5:  "GBP",
		6:  "HUF",
		7:  "PLN",
		8:  "RON",
		9:  "SEK",
		10: "CHF",
		11: "ISK",
		12: "NOK",
		13: "HRK",
		14: "TRY",
		15: "AUD",
		16: "BRL",
		17: "CAD",
		18: "CNY",
		19: "HKD",
		20: "IDR",
		21: "ILS",
		22: "INR",
		23: "KRW",
		24: "MXN",
		25: "MYR",
		26: "NZD",
		27: "PHP",
		28: "SGD",
		29: "THB",
		30: "ZAR",
	}
	Currencies_value = map[string]int32{
		"USD": 0,
		"JPY": 1,
		"BGN": 2,
		"CZK": 3,
		"DKK": 4,
		"GBP": 5,
		"HUF": 6,
		"PLN": 7,
		"RON": 8,
		"SEK": 9,
		"CHF": 10,
		"ISK": 11,
		"NOK": 12,
		"HRK": 13,
		"TRY": 14,
		"AUD": 15,
		"BRL": 16,
		"CAD": 17,
		"CNY": 18,
		"HKD": 19,
		"IDR": 20,
		"ILS": 21,
		"INR": 22,
		"KRW": 23,
		"MXN": 24,
		"MYR": 25,
		"NZD": 26,
		"PHP": 27,
		"SGD": 28,
		"THB": 29,
		"ZAR": 30,
	}
)

func (x Currencies) Enum() *Currencies {
	p := new(Currencies)
	*p = x
	return p
}

func (x Currencies) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currencies) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_currency_proto_enumTypes[0].Descriptor()
}

func (Currencies) Type() protoreflect.EnumType {
	return &file_proto_currency_proto_enumTypes[0]
}

func (x Currencies) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currencies.Descriptor instead.
func (Currencies) EnumDescriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{0}
}

type ExchangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_currency_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ExchangeRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ExchangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate float32 `protobuf:"fixed32,1,opt,name=Rate,proto3" json:"Rate,omitempty"`
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_currency_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeResponse) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

var File_proto_currency_proto protoreflect.FileDescriptor

var file_proto_currency_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x35, 0x0a, 0x0f, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x22, 0x26, 0x0a, 0x10, 0x45,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x52, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x52,
	0x61, 0x74, 0x65, 0x2a, 0xa3, 0x02, 0x0a, 0x0a, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x53, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4a,
	0x50, 0x59, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x47, 0x4e, 0x10, 0x02, 0x12, 0x07, 0x0a,
	0x03, 0x43, 0x5a, 0x4b, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x4b, 0x4b, 0x10, 0x04, 0x12,
	0x07, 0x0a, 0x03, 0x47, 0x42, 0x50, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x48, 0x55, 0x46, 0x10,
	0x06, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x4c, 0x4e, 0x10, 0x07, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x4f,
	0x4e, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x45, 0x4b, 0x10, 0x09, 0x12, 0x07, 0x0a, 0x03,
	0x43, 0x48, 0x46, 0x10, 0x0a, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x53, 0x4b, 0x10, 0x0b, 0x12, 0x07,
	0x0a, 0x03, 0x4e, 0x4f, 0x4b, 0x10, 0x0c, 0x12, 0x07, 0x0a, 0x03, 0x48, 0x52, 0x4b, 0x10, 0x0d,
	0x12, 0x07, 0x0a, 0x03, 0x54, 0x52, 0x59, 0x10, 0x0e, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x55, 0x44,
	0x10, 0x0f, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x52, 0x4c, 0x10, 0x10, 0x12, 0x07, 0x0a, 0x03, 0x43,
	0x41, 0x44, 0x10, 0x11, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x4e, 0x59, 0x10, 0x12, 0x12, 0x07, 0x0a,
	0x03, 0x48, 0x4b, 0x44, 0x10, 0x13, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x44, 0x52, 0x10, 0x14, 0x12,
	0x07, 0x0a, 0x03, 0x49, 0x4c, 0x53, 0x10, 0x15, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x52, 0x10,
	0x16, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x52, 0x57, 0x10, 0x17, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x58,
	0x4e, 0x10, 0x18, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x59, 0x52, 0x10, 0x19, 0x12, 0x07, 0x0a, 0x03,
	0x4e, 0x5a, 0x44, 0x10, 0x1a, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x48, 0x50, 0x10, 0x1b, 0x12, 0x07,
	0x0a, 0x03, 0x53, 0x47, 0x44, 0x10, 0x1c, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x48, 0x42, 0x10, 0x1d,
	0x12, 0x07, 0x0a, 0x03, 0x5a, 0x41, 0x52, 0x10, 0x1e, 0x32, 0x59, 0x0a, 0x08, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x4d, 0x0a, 0x0c, 0x4d, 0x61, 0x6b, 0x65, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_currency_proto_rawDescOnce sync.Once
	file_proto_currency_proto_rawDescData = file_proto_currency_proto_rawDesc
)

func file_proto_currency_proto_rawDescGZIP() []byte {
	file_proto_currency_proto_rawDescOnce.Do(func() {
		file_proto_currency_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_currency_proto_rawDescData)
	})
	return file_proto_currency_proto_rawDescData
}

var file_proto_currency_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_currency_proto_goTypes = []interface{}{
	(Currencies)(0),          // 0: grpc_service.Currencies
	(*ExchangeRequest)(nil),  // 1: grpc_service.ExchangeRequest
	(*ExchangeResponse)(nil), // 2: grpc_service.ExchangeResponse
}
var file_proto_currency_proto_depIdxs = []int32{
	1, // 0: grpc_service.Currency.MakeExchange:input_type -> grpc_service.ExchangeRequest
	2, // 1: grpc_service.Currency.MakeExchange:output_type -> grpc_service.ExchangeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_currency_proto_init() }
func file_proto_currency_proto_init() {
	if File_proto_currency_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_currency_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_currency_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_currency_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_currency_proto_goTypes,
		DependencyIndexes: file_proto_currency_proto_depIdxs,
		EnumInfos:         file_proto_currency_proto_enumTypes,
		MessageInfos:      file_proto_currency_proto_msgTypes,
	}.Build()
	File_proto_currency_proto = out.File
	file_proto_currency_proto_rawDesc = nil
	file_proto_currency_proto_goTypes = nil
	file_proto_currency_proto_depIdxs = nil
}
