// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/currency.proto

package grpcservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Currency_MakeExchange_FullMethodName = "/grpcservice.Currency/MakeExchange"
	Currency_Subscriber_FullMethodName   = "/grpcservice.Currency/Subscriber"
)

// CurrencyClient is the client API for Currency service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyClient interface {
	MakeExchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error)
	// allows a client to subscribe for changes when the rate changes a response will be sent
	Subscriber(ctx context.Context, opts ...grpc.CallOption) (Currency_SubscriberClient, error)
}

type currencyClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyClient(cc grpc.ClientConnInterface) CurrencyClient {
	return &currencyClient{cc}
}

func (c *currencyClient) MakeExchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error) {
	out := new(ExchangeResponse)
	err := c.cc.Invoke(ctx, Currency_MakeExchange_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyClient) Subscriber(ctx context.Context, opts ...grpc.CallOption) (Currency_SubscriberClient, error) {
	stream, err := c.cc.NewStream(ctx, &Currency_ServiceDesc.Streams[0], Currency_Subscriber_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &currencySubscriberClient{stream}
	return x, nil
}

type Currency_SubscriberClient interface {
	Send(*ExchangeRequest) error
	Recv() (*StreamExchangeResponse, error)
	grpc.ClientStream
}

type currencySubscriberClient struct {
	grpc.ClientStream
}

func (x *currencySubscriberClient) Send(m *ExchangeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *currencySubscriberClient) Recv() (*StreamExchangeResponse, error) {
	m := new(StreamExchangeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CurrencyServer is the server API for Currency service.
// All implementations should embed UnimplementedCurrencyServer
// for forward compatibility
type CurrencyServer interface {
	MakeExchange(context.Context, *ExchangeRequest) (*ExchangeResponse, error)
	// allows a client to subscribe for changes when the rate changes a response will be sent
	Subscriber(Currency_SubscriberServer) error
}

// UnimplementedCurrencyServer should be embedded to have forward compatible implementations.
type UnimplementedCurrencyServer struct {
}

func (UnimplementedCurrencyServer) MakeExchange(context.Context, *ExchangeRequest) (*ExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeExchange not implemented")
}
func (UnimplementedCurrencyServer) Subscriber(Currency_SubscriberServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscriber not implemented")
}

// UnsafeCurrencyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyServer will
// result in compilation errors.
type UnsafeCurrencyServer interface {
	mustEmbedUnimplementedCurrencyServer()
}

func RegisterCurrencyServer(s grpc.ServiceRegistrar, srv CurrencyServer) {
	s.RegisterService(&Currency_ServiceDesc, srv)
}

func _Currency_MakeExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServer).MakeExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Currency_MakeExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServer).MakeExchange(ctx, req.(*ExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Currency_Subscriber_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CurrencyServer).Subscriber(&currencySubscriberServer{stream})
}

type Currency_SubscriberServer interface {
	Send(*StreamExchangeResponse) error
	Recv() (*ExchangeRequest, error)
	grpc.ServerStream
}

type currencySubscriberServer struct {
	grpc.ServerStream
}

func (x *currencySubscriberServer) Send(m *StreamExchangeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *currencySubscriberServer) Recv() (*ExchangeRequest, error) {
	m := new(ExchangeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Currency_ServiceDesc is the grpc.ServiceDesc for Currency service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Currency_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcservice.Currency",
	HandlerType: (*CurrencyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeExchange",
			Handler:    _Currency_MakeExchange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscriber",
			Handler:       _Currency_Subscriber_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/currency.proto",
}
